import type {
  Category,
  Creator,
  LiveSession,
  Testimonial,
  FAQItem,
  Campaign,
} from '@/types';

export const SITE = {
  name: 'Fanitt',
  url: 'www.fanitt.com',
};

export const NAV_LINKS = [
  { label: 'Feed', href: '/feed' },
  { label: 'Explore Creators', href: '/explore' },
  { label: 'Live Sessions', href: '/sessions' },
  { label: 'Communities', href: '/communities' },
  { label: 'Categories', href: '#categories' },
  { label: 'Campaigns', href: '/campaigns' },
  { label: 'For Brands', href: '#for-brands' },
  { label: 'For Creators', href: '#for-creators' },
];
export const CATEGORIES: Category[] = [
  { label: 'Fitness & Health', icon: 'Dumbbell' },
  { label: 'Music Production', icon: 'Music2' },
  { label: 'Personal Finance', icon: 'PiggyBank' },
  { label: 'Art & Design', icon: 'Palette' },
  { label: 'Comedy', icon: 'Mic2' },
  { label: 'Career Mentorship', icon: 'Briefcase' },
  { label: 'Cooking', icon: 'ChefHat' },
  { label: 'Gaming', icon: 'Gamepad2' },
  { label: 'Photography', icon: 'Camera' },
  { label: 'Business Coaching', icon: 'TrendingUp' },
];

export const CREATORS: Creator[] = [
  {
    name: 'Rhea Kapoor',
    specialty: 'Strength & Mobility Coaching',
    seed: 'rhea-kapoor',
    followers: '48K',
    slug: 'rhea-kapoor',
    bio: "I help desk-bound professionals move without pain again. Strength & mobility coach, ex-national athlete, 300+ 1:1 sessions delivered.",
    category: 'Fitness & Health',
    rating: 4.9,
    reviewCount: 312,
    location: 'Mumbai, India',
    socials: { instagram: 'https://instagram.com', linkedin: 'https://linkedin.com' },
  },
  {
    name: 'Aarav Mehta',
    specialty: 'Lo-fi & Beat Production',
    seed: 'aarav-mehta',
    followers: '112K',
    slug: 'aarav-mehta',
    bio: 'Self-taught producer turned label-signed artist. I teach the exact lo-fi workflow that got 3 of my beats picked up by indie labels.',
    category: 'Music Production',
    rating: 4.8,
    reviewCount: 184,
    location: 'Bengaluru, India',
    socials: { instagram: 'https://instagram.com', youtube: 'https://youtube.com' },
  },
  {
    name: 'Simran Oberoi',
    specialty: 'Personal Finance for Freelancers',
    seed: 'simran-oberoi',
    followers: '76K',
    slug: 'simran-oberoi',
    bio: 'Chartered accountant turned finance educator. I make taxes, GST and savings actually make sense for freelancers and creators.',
    category: 'Personal Finance',
    rating: 4.9,
    reviewCount: 401,
    location: 'Delhi, India',
    socials: { instagram: 'https://instagram.com', linkedin: 'https://linkedin.com', facebook: 'https://facebook.com' },
  },
  {
    name: 'Kabir Anand',
    specialty: 'Digital Illustration',
    seed: 'kabir-anand',
    followers: '203K',
    slug: 'kabir-anand',
    bio: 'Ex-Ubisoft concept artist. Now teaching character design to the next generation of game and animation artists.',
    category: 'Art & Design',
    rating: 5.0,
    reviewCount: 267,
    location: 'Pune, India',
    socials: { instagram: 'https://instagram.com', youtube: 'https://youtube.com', linkedin: 'https://linkedin.com' },
  },
  {
    name: 'Devika Rao',
    specialty: 'Stand-up & Improv',
    seed: 'devika-rao',
    followers: '89K',
    slug: 'devika-rao',
    bio: "Stand-up comedian, 867K fans, and now teaching the timing and writing craft behind the jokes that actually land.",
    category: 'Comedy',
    rating: 4.7,
    reviewCount: 156,
    location: 'Mumbai, India',
    socials: { instagram: 'https://instagram.com', facebook: 'https://facebook.com' },
  },
  {
    name: 'Yash Malhotra',
    specialty: 'Career Switch Mentorship',
    seed: 'yash-malhotra',
    followers: '34K',
    slug: 'yash-malhotra',
    bio: 'Helped 200+ people switch careers into tech without a CS degree. Ex-recruiter, now full-time mentor.',
    category: 'Career Mentorship',
    rating: 4.8,
    reviewCount: 98,
    location: 'Gurugram, India',
    socials: { linkedin: 'https://linkedin.com' },
  },
  {
    name: 'Ananya Iyer',
    specialty: 'Regional Home Cooking',
    seed: 'ananya-iyer',
    followers: '156K',
    slug: 'ananya-iyer',
    bio: 'Home chef sharing regional recipes passed down three generations — no fancy equipment, just real technique.',
    category: 'Cooking',
    rating: 4.9,
    reviewCount: 223,
    location: 'Chennai, India',
    socials: { instagram: 'https://instagram.com', youtube: 'https://youtube.com' },
  },
  {
    name: 'Rohan Bhatia',
    specialty: 'Competitive Gaming Coaching',
    seed: 'rohan-bhatia',
    followers: '267K',
    slug: 'rohan-bhatia',
    bio: 'Former pro esports player. I review VODs and build aim/game-sense training plans for climbers stuck in mid-rank.',
    category: 'Gaming',
    rating: 4.7,
    reviewCount: 341,
    location: 'Hyderabad, India',
    socials: { instagram: 'https://instagram.com', youtube: 'https://youtube.com' },
  },
  {
    name: 'Meher Chawla',
    specialty: 'Portrait Photography',
    seed: 'meher-chawla',
    followers: '61K',
    slug: 'meher-chawla',
    bio: 'Portrait & editorial photographer. I teach natural light technique — no studio required.',
    category: 'Photography',
    rating: 4.9,
    reviewCount: 132,
    location: 'Jaipur, India',
    socials: { instagram: 'https://instagram.com', facebook: 'https://facebook.com' },
  },
  {
    name: 'Nikhil Sethi',
    specialty: 'D2C Growth Strategy',
    seed: 'nikhil-sethi',
    followers: '92K',
    slug: 'nikhil-sethi',
    bio: 'Scaled a D2C skincare brand to 8 figures before turning full-time growth advisor for early-stage founders.',
    category: 'Business Coaching',
    rating: 4.8,
    reviewCount: 87,
    location: 'Mumbai, India',
    socials: { linkedin: 'https://linkedin.com', instagram: 'https://instagram.com' },
  },
];

export const LIVE_SESSIONS: LiveSession[] = [
  {
    title: 'Mobility Reset for Desk Workers',
    hook: 'The 20-minute reset engineers keep coming back to.',
    creatorSeed: 'rhea-kapoor',
    creatorName: 'Rhea Kapoor',
    creatorTag: 'Strength & Mobility Coach',
    category: 'Fitness & Health',
    day: 'Wed, 9th Jul',
    time: '7:00 AM',
    duration: '20 Min',
    price: '₹149 per session',
    free: false,
    stat: '22K+ bookings',
    formatBadge: '20-min live session',
  },
  {
    title: 'Build Your First Lo-fi Loop',
    hook: 'The beat-making sprint that got picked up by 3 labels.',
    creatorSeed: 'aarav-mehta',
    creatorName: 'Aarav Mehta',
    creatorTag: 'Music Producer',
    category: 'Music Production',
    day: 'Wed, 9th Jul',
    time: '6:30 PM',
    duration: '60 Min',
    price: '₹499 per session',
    free: false,
    stat: '17K followers',
    formatBadge: '6-week live cohort',
  },
  {
    title: 'Taxes 101 for Freelance Creators',
    hook: 'The finance sprint MIT\'s own alumni recommended.',
    creatorSeed: 'simran-oberoi',
    creatorName: 'Simran Oberoi',
    creatorTag: 'Finance Coach',
    category: 'Personal Finance',
    day: 'Thu, 10th Jul',
    time: '8:00 PM',
    duration: '45 Min',
    price: 'FREE',
    free: true,
    stat: '76K followers',
    formatBadge: '~8-week sprint',
  },
  {
    title: 'Character Design Sprint',
    hook: 'She got the studio gig. Now she\'s pulling you through the door.',
    creatorSeed: 'kabir-anand',
    creatorName: 'Kabir Anand',
    creatorTag: 'Digital Illustrator',
    category: 'Art & Design',
    day: 'Thu, 10th Jul',
    time: '5:00 PM',
    duration: '90 Min',
    price: '₹399 per session',
    free: false,
    stat: 'Ex-Ubisoft artist',
    formatBadge: '6-week cohort',
  },
  {
    title: 'Improv Warm-Up Jam',
    hook: '867K fans found their timing here. Yours is next.',
    creatorSeed: 'devika-rao',
    creatorName: 'Devika Rao',
    creatorTag: 'Stand-up Comedian',
    category: 'Comedy',
    day: 'Fri, 11th Jul',
    time: '7:30 PM',
    duration: '60 Min',
    price: '₹249 per session',
    free: false,
    stat: '867K followers',
    formatBadge: '1:1 · 5 slots left',
  },
  {
    title: 'Resume Teardown: Live Reviews',
    hook: 'The 30-minute teardown before you hit apply.',
    creatorSeed: 'yash-malhotra',
    creatorName: 'Yash Malhotra',
    creatorTag: 'Career Mentor',
    category: 'Career Mentorship',
    day: 'Fri, 11th Jul',
    time: '9:00 AM',
    duration: '30 Min',
    price: 'FREE',
    free: true,
    stat: '34K followers',
    formatBadge: '30-min live session',
  },
  {
    title: 'Weeknight Thali in 40 Minutes',
    hook: 'The regional thali recipe her fans begged her to teach.',
    creatorSeed: 'ananya-iyer',
    creatorName: 'Ananya Iyer',
    creatorTag: 'Home Chef',
    category: 'Cooking',
    day: 'Sat, 12th Jul',
    time: '6:00 PM',
    duration: '40 Min',
    price: '₹299 per session',
    free: false,
    stat: '156K followers',
    formatBadge: '40-min live session',
  },
  {
    title: 'Aim Training & VOD Review',
    hook: 'The VOD review that got 40 fans to rank up this month.',
    creatorSeed: 'rohan-bhatia',
    creatorName: 'Rohan Bhatia',
    creatorTag: 'Esports Coach',
    category: 'Gaming',
    day: 'Sat, 12th Jul',
    time: '9:00 PM',
    duration: '45 Min',
    price: '₹349 per session',
    free: false,
    stat: '267K followers',
    formatBadge: '1:1 · 45-min session',
  },
];

export const FREE_SESSIONS: LiveSession[] = [
  {
    title: 'Taxes 101 for Freelance Creators',
    hook: "The finance sprint MIT's own alumni recommended.",
    creatorSeed: 'simran-oberoi',
    creatorName: 'Simran Oberoi',
    creatorTag: 'Finance Coach',
    category: 'Personal Finance',
    day: 'Thu, 10th Jul',
    time: '8:00 PM',
    duration: '45 Min',
    price: 'FREE',
    free: true,
    stat: '76K followers',
    formatBadge: '~8-week sprint',
  },
  {
    title: 'Resume Teardown: Live Reviews',
    hook: 'The 30-minute teardown before you hit apply.',
    creatorSeed: 'yash-malhotra',
    creatorName: 'Yash Malhotra',
    creatorTag: 'Career Mentor',
    category: 'Career Mentorship',
    day: 'Fri, 11th Jul',
    time: '9:00 AM',
    duration: '30 Min',
    price: 'FREE',
    free: true,
    stat: '34K followers',
    formatBadge: '30-min live session',
  },
  {
    title: 'Sketch to Character in 20 Minutes',
    hook: 'A first taste of the character design cohort.',
    creatorSeed: 'kabir-anand',
    creatorName: 'Kabir Anand',
    creatorTag: 'Digital Illustrator',
    category: 'Art & Design',
    day: 'Sat, 12th Jul',
    time: '5:00 PM',
    duration: '20 Min',
    price: '₹399',
    free: false,
    stat: 'Ex-Ubisoft artist',
    formatBadge: '20-min live session',
  },
  {
    title: 'Crop Sensor vs Full Frame, Explained',
    hook: 'The gear question every beginner asks first.',
    creatorSeed: 'meher-chawla',
    creatorName: 'Meher Chawla',
    creatorTag: 'Portrait Photographer',
    category: 'Photography',
    day: 'Sat, 12th Jul',
    time: '11:00 AM',
    duration: '25 Min',
    price: 'FREE',
    free: true,
    stat: '61K followers',
    formatBadge: '25-min live session',
  },
  {
    title: 'Warm-Up Routine Before Ranked',
    hook: 'The 15-minute drill Rohan runs before every match.',
    creatorSeed: 'rohan-bhatia',
    creatorName: 'Rohan Bhatia',
    creatorTag: 'Esports Coach',
    category: 'Gaming',
    day: 'Sun, 13th Jul',
    time: '6:00 PM',
    duration: '15 Min',
    price: '₹199',
    free: false,
    stat: '267K followers',
    formatBadge: '15-min live session',
  },
  {
    title: 'D2C Growth Playbook in 15 Minutes',
    hook: 'The framework Nikhil used before scaling to 8 figures.',
    creatorSeed: 'nikhil-sethi',
    creatorName: 'Nikhil Sethi',
    creatorTag: 'D2C Growth Strategist',
    category: 'Business Coaching',
    day: 'Mon, 14th Jul',
    time: '10:00 AM',
    duration: '15 Min',
    price: 'FREE',
    free: true,
    stat: '92K followers',
    formatBadge: '15-min live session',
  },
];

// For the "Book a 1:1 Session" grid — reuses the creator roster.
export const ONE_TO_ONE_CREATORS = CREATORS;

export const FOR_CREATORS_POINTS = [
  'Build a public portfolio with reels, photos & featured work',
  'Host free public sessions, paid sessions, or 1-to-1s — you set the price',
  'Get paid safely — funds only release once a brand approves your work',
  'Earn from live donations, paid sessions and brand collaborations, all in one payout',
  'Track bookings, earnings and reviews from a single creator dashboard',
  'Running an agency? Onboard your roster with a referral code and earn ongoing commission',
];

export const FOR_BRANDS_POINTS = [
  'Search & filter creators by category, location, followers and availability',
  'Launch a campaign in minutes and invite the right creators directly',
  'Every rupee is held in escrow — released only after you approve the work',
  'Track budgets, active collaborations and payments from one dashboard',
  'No business email or website required to get started',
  'Rate creators after every collaboration to build a trusted long-term roster',
];

export const TESTIMONIALS: Testimonial[] = [
  {
    quote:
      "I went from posting for free to booking 1-to-1 sessions every week. My fans finally have a way to pay me directly.",
    name: 'Rhea Kapoor',
    role: 'Fitness Creator',
    seed: 'rhea-kapoor',
  },
  {
    quote:
      "We ran our first micro-influencer campaign without a single email chain. Fanitt's escrow made the brand side painless.",
    name: 'Nikhil Sethi',
    role: 'Brand Manager, D2C Skincare',
    seed: 'nikhil-sethi',
  },
  {
    quote:
      "Joining a free session was the easiest first step. I was watching live within two minutes of signing up.",
    name: 'Priya Nair',
    role: 'Fan',
    seed: 'priya-nair',
  },
  {
    quote:
      "The donation feature during live sessions changed how I think about free content — my community shows up for me.",
    name: 'Devika Rao',
    role: 'Comedy Creator',
    seed: 'devika-rao',
  },
  {
    quote:
      'As an agency, tracking commission across 30+ creators used to be a spreadsheet nightmare. Now it is automatic.',
    name: 'Karan Vora',
    role: 'Talent Agency Owner',
    seed: 'karan-vora',
  },
  {
    quote:
      "Booking a portrait session with Meher felt as easy as ordering food. Paid, scheduled, done.",
    name: 'Aditya Singh',
    role: 'Fan',
    seed: 'aditya-singh',
  },
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    question: 'What is Fanitt?',
    answer:
      "Fanitt is a platform where creators, brands and fans collaborate directly. Fans discover creators and join live sessions, creators build a public portfolio and earn through sessions and brand deals, and brands find and pay creators safely — all in one place.",
  },
  {
    question: 'How do I book a live session?',
    answer:
      'Browse a creator profile or the live sessions list, pick a free or paid slot, and confirm — you\'ll get a reminder before the session goes live on web or the Fanitt app.',
  },
  {
    question: 'Is my payment protected when I work with a brand?',
    answer:
      'Yes. For brand collaborations, the budget is held in escrow by Fanitt and only released to the creator once the brand reviews and approves the submitted work.',
  },
  {
    question: 'Can I upgrade from a Fan account to a Creator or Brand account?',
    answer:
      'Yes — any Fan account can upgrade to Creator or Brand from the dashboard at any time, no separate sign-up required.',
  },
  {
    question: 'Do brands need a business email or website to join?',
    answer:
      "No. Fanitt is built for the long tail of small and micro brands — you can launch a campaign without a business email or website.",
  },
  {
    question: 'Is there a Fanitt app?',
    answer: 'Fanitt is available as a responsive web app today, with native iOS and Android apps on the way.',
  },
];

export const CAMPAIGNS: Campaign[] = [
  {
    id: 'summer-skincare-drop',
    title: 'Summer Skincare Drop — Reel Collab',
    brandName: 'Glowlab Cosmetics',
    brandSeed: 'glowlab-cosmetics',
    category: 'Fitness & Health',
    budget: '₹40,000 – ₹60,000',
    duration: '2-week campaign',
    location: 'Remote',
    creatorType: 'Fitness & lifestyle creators, 20K+ followers',
    description:
      'Looking for 3 fitness creators to feature our new SPF body range in a single reel each. Product provided, usage rights for 3 months.',
    postedDaysAgo: 2,
    applicants: 14,
  },
  {
    id: 'd2c-app-launch',
    title: 'App Launch Explainer Video',
    brandName: 'Nudge Finance',
    brandSeed: 'nudge-finance',
    category: 'Personal Finance',
    budget: '₹25,000 flat',
    duration: '1 video, 2-week turnaround',
    location: 'Remote',
    creatorType: 'Finance educators, any follower size',
    description:
      "We're launching a savings app for freelancers and want a finance creator to break down how it works in a 3-minute explainer.",
    postedDaysAgo: 4,
    applicants: 9,
  },
  {
    id: 'gaming-headset-review',
    title: 'Gaming Headset — Honest Review',
    brandName: 'Sonix Gear',
    brandSeed: 'sonix-gear',
    category: 'Gaming',
    budget: '₹18,000 + product',
    duration: '1 video',
    location: 'Remote',
    creatorType: 'Gaming creators, competitive/FPS audience',
    description: 'Send us your honest take on our new wireless headset — good, bad, all of it. No script required.',
    postedDaysAgo: 1,
    applicants: 22,
  },
  {
    id: 'home-cooking-series',
    title: '5-Part Regional Cooking Series',
    brandName: 'Masala Box',
    brandSeed: 'masala-box',
    category: 'Cooking',
    budget: '₹1,20,000 total',
    duration: '5-week series',
    location: 'Remote',
    creatorType: 'Home chefs with a regional cuisine focus',
    description: 'Looking for one home chef to run a 5-part series using our spice kits — full creative freedom on recipes.',
    postedDaysAgo: 6,
    applicants: 31,
  },
  {
    id: 'career-coaching-webinar',
    title: 'Co-hosted Career Webinar',
    brandName: 'Hirewise',
    brandSeed: 'hirewise',
    category: 'Career Mentorship',
    budget: '₹30,000',
    duration: '1 live session (60 min)',
    location: 'Remote',
    creatorType: 'Career mentors / recruiters',
    description: 'We want to co-host a live webinar on breaking into tech without a CS degree — you bring the audience and story, we bring the platform.',
    postedDaysAgo: 3,
    applicants: 6,
  },
  {
    id: 'photography-gear-unboxing',
    title: 'Camera Gear Unboxing + Review',
    brandName: 'LensCraft',
    brandSeed: 'lenscraft',
    category: 'Photography',
    budget: '₹22,000 + gear',
    duration: '1 video',
    location: 'Remote',
    creatorType: 'Photography creators, any niche',
    description: 'New mirrorless lens launching next month — want an honest first-impressions review before the public launch.',
    postedDaysAgo: 5,
    applicants: 11,
  },
];
